name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload_to_blob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Setting up Azure CLI"
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Upload file to Blob Storage
        run: |
          echo "Uploading files to Blob Storage"
          az storage blob upload-batch --destination ${{ secrets.AZURE_CONTAINER_NAME }} --source ./ --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --overwrite

      - name: Clean up local files
        run: |
          echo "Cleaning up"
          rm -rf *
